# Generated by Django 4.0.5 on 2022-11-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mrp', models.IntegerField(default=1)),
                ('offer_price', models.IntegerField(default=1)),
                ('offer_percentage', models.IntegerField(default=1)),
                ('image', models.ImageField(null='True', upload_to='media/')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
                ('subcategory_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='category.subcategory')),
                ('subsubcategory_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='category.subsubcategory')),
            ],
        ),
    ]
