# Generated by Django 4.0.5 on 2022-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
