# Generated by Django 4.0.5 on 2022-12-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_reviews_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='product',
            new_name='product_name',
        ),
    ]
