# Generated by Django 4.0.5 on 2022-12-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_reviews_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
    ]
