# Generated by Django 4.0.5 on 2022-11-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='zipcode',
            field=models.IntegerField(default=1),
        ),
    ]
