# Generated by Django 4.0.5 on 2022-12-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customer_info_email_alter_customer_info_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='locality',
            new_name='apartmentname',
        ),
    ]
