# Generated by Django 4.0.5 on 2022-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_reviews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
