# Generated by Django 4.0.5 on 2022-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_reviews_slug_alter_reviews_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='product_name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='product_name',
            field=models.ManyToManyField(blank=True, to='product.product', verbose_name='product'),
        ),
    ]
