# Generated by Django 4.0.5 on 2022-12-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0008_alter_reviews_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='category.brands'),
        ),
    ]
