# Generated by Django 4.0.5 on 2023-03-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('BLUE', 'BLUE'), ('PINK', 'PINK'), ('MAROON', 'MAROON'), ('IVORY', 'IVORY'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('GOLDEN', 'GOLDEN'), ('BROWN', 'BROWN'), ('SILVER', 'SILVER')], default='WHITE', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('LARGE', 'LARGE'), ('MEDIUM', 'MEDIUM'), ('SMALL', 'SMALL')], default='SMALL', max_length=100),
        ),
    ]
