# Generated by Django 4.0.5 on 2023-03-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_color_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('OUT OF STOCK', 'OUT OF STOCK')], default='IN STOCK', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='DBMS1', max_length=100),
        ),
    ]
