# Generated by Django 4.0.5 on 2023-03-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_subsubcategory_name'),
        ('product', '0014_alter_product_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='category.subcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsubcategory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='category.subsubcategory'),
        ),
    ]
