# Generated by Django 4.0.5 on 2023-03-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_subcategory_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'WHITE'), ('BLUE', 'BLUE'), ('PINK', 'PINK'), ('MAROON', 'MAROON'), ('IVORY', 'IVORY'), ('RED', 'RED'), ('ORANGE', 'ORANGE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('GOLDEN', 'GOLDEN'), ('BROWN', 'BROWN'), ('SILVER', 'SILVER')], default='WHITE', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('LARGE', 'LARGE'), ('MEDIUM', 'MEDIUM'), ('SMALL', 'SMALL')], default='SMALL', max_length=100),
        ),
    ]
