# Generated by Django 4.0.5 on 2023-03-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_brands_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='code',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(blank=None, default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=None, default='None', max_length=100),
        ),
    ]
