# Generated by Django 4.0.5 on 2023-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
