# Generated by Django 4.0.5 on 2022-12-12 11:18

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('footerlogo', models.ImageField(upload_to='logo')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, validators=[about.models.only_int])),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('otherPhone', models.CharField(help_text='Separate phone number with (,) Ex: +61 3 1234 5678 , +12 3 1234 5678.......', max_length=1000)),
            ],
        ),
    ]
