# Generated by Django 4.0.5 on 2023-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_item',
            field=models.ManyToManyField(to='product.cart'),
        ),
    ]
