# Generated by Django 4.0.5 on 2022-12-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_brands'),
        ('order', '0003_remove_orderitem_product_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quntity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='update_order',
            name='prod_orders',
        ),
        migrations.AddField(
            model_name='update_order',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='update_order',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='update_order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='update_order',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='update_order',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='update_order',
            name='product',
            field=models.ManyToManyField(to='product.cart', verbose_name='product_order'),
        ),
        migrations.AddField(
            model_name='update_order',
            name='quntity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='update_order',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='update_order',
            name='zipcode',
            field=models.IntegerField(default=1),
        ),
    ]
