# Generated by Django 4.0.5 on 2022-12-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='phone',
            new_name='mobile',
        ),
    ]
