# Generated by Django 4.0.5 on 2022-12-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_address_remove_orderitem_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update_order',
            name='updt_id',
        ),
    ]
