# Generated by Django 4.0.5 on 2022-12-02 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_locality_customer_info_apartmentname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_rename_phone_orderitem_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='state',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='product_pyment_id'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quntity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='zipcode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to=settings.AUTH_USER_MODEL),
        ),
    ]
