# Generated by Django 4.0.5 on 2023-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_time_alter_orderitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
