# Generated by Django 4.0.5 on 2022-12-02 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0005_remove_orderitem_country_remove_orderitem_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updt_id', models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='updt_pyment_id')),
                ('updt_date', models.DateTimeField(auto_now_add=True)),
                ('prod_orders', models.ManyToManyField(to='order.orderitem', verbose_name='product_order')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
