# Generated by Django 4.0.5 on 2023-03-29 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_date_orderitem_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 12, 47, 12, 117814)),
        ),
    ]
