# Generated by Django 4.0.5 on 2023-03-31 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0006_alter_orderitem_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 11, 55, 26, 161268)),
        ),
        migrations.AlterField(
            model_name='update_order',
            name='product',
            field=models.ManyToManyField(to='product.cart'),
        ),
    ]
