# Generated by Django 4.0.5 on 2023-03-31 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_update_order_amount_alter_orderitem_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update_order',
            name='amount',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 12, 21, 33, 243037)),
        ),
    ]
