# Generated by Django 4.0.5 on 2022-12-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_orderitem_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update_order',
            name='quntity',
        ),
    ]
