# Generated by Django 4.0.5 on 2022-12-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_brands'),
        ('order', '0015_remove_orderitem_address_remove_orderitem_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cartitem',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
