# Generated by Django 4.0.5 on 2023-03-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderitem_code_orderitem_color_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
